port = 8181
site = "KendellFabrici.us"
per_page = 5
admin = "../static/admin"
theme = "../static/hyde"
upload = "/home/kendell/Desktop/uploads"
session = ["ADF@#$123Mdskoek"]

[sqlite]
path = "publish.db"

[mysql]
username = "publish"
password = "publish"
db = "publish"
max_idle = 5
max_open = 10