port = 8181
site = "KendellFabrici.us"
admin = "../static/admin"
theme = "../static/hyde"
upload = "~/Desktop/uploads"
session = ["ADF@#$123Mdskoek"]

[sqlite]
path = "publish.db"

[mysql]
username = "publish"
password = "publish"
db = "publish"